# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import portfolio_pb2 as portfolio__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in portfolio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PortfolioServiceStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
                '/portfolio.PortfolioService/Authenticate',
                request_serializer=portfolio__pb2.AuthRequest.SerializeToString,
                response_deserializer=portfolio__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.CreatePortfolio = channel.unary_unary(
                '/portfolio.PortfolioService/CreatePortfolio',
                request_serializer=portfolio__pb2.CreatePortfolioRequest.SerializeToString,
                response_deserializer=portfolio__pb2.Portfolio.FromString,
                _registered_method=True)
        self.LoadPortfolio = channel.unary_unary(
                '/portfolio.PortfolioService/LoadPortfolio',
                request_serializer=portfolio__pb2.LoadPortfolioRequest.SerializeToString,
                response_deserializer=portfolio__pb2.Portfolio.FromString,
                _registered_method=True)
        self.ListPortfolios = channel.unary_unary(
                '/portfolio.PortfolioService/ListPortfolios',
                request_serializer=portfolio__pb2.ListPortfoliosRequest.SerializeToString,
                response_deserializer=portfolio__pb2.ListPortfoliosResponse.FromString,
                _registered_method=True)
        self.RunStrategy = channel.unary_unary(
                '/portfolio.PortfolioService/RunStrategy',
                request_serializer=portfolio__pb2.RunStrategyRequest.SerializeToString,
                response_deserializer=portfolio__pb2.StrategyResult.FromString,
                _registered_method=True)
        self.GetPriceHistory = channel.unary_unary(
                '/portfolio.PortfolioService/GetPriceHistory',
                request_serializer=portfolio__pb2.GetPriceHistoryRequest.SerializeToString,
                response_deserializer=portfolio__pb2.PriceHistory.FromString,
                _registered_method=True)
        self.RunBacktest = channel.unary_unary(
                '/portfolio.PortfolioService/RunBacktest',
                request_serializer=portfolio__pb2.BacktestRequest.SerializeToString,
                response_deserializer=portfolio__pb2.BacktestResult.FromString,
                _registered_method=True)


class PortfolioServiceServicer(object):
    """Service
    """

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadPortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPortfolios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPriceHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortfolioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=portfolio__pb2.AuthRequest.FromString,
                    response_serializer=portfolio__pb2.AuthResponse.SerializeToString,
            ),
            'CreatePortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePortfolio,
                    request_deserializer=portfolio__pb2.CreatePortfolioRequest.FromString,
                    response_serializer=portfolio__pb2.Portfolio.SerializeToString,
            ),
            'LoadPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadPortfolio,
                    request_deserializer=portfolio__pb2.LoadPortfolioRequest.FromString,
                    response_serializer=portfolio__pb2.Portfolio.SerializeToString,
            ),
            'ListPortfolios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPortfolios,
                    request_deserializer=portfolio__pb2.ListPortfoliosRequest.FromString,
                    response_serializer=portfolio__pb2.ListPortfoliosResponse.SerializeToString,
            ),
            'RunStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.RunStrategy,
                    request_deserializer=portfolio__pb2.RunStrategyRequest.FromString,
                    response_serializer=portfolio__pb2.StrategyResult.SerializeToString,
            ),
            'GetPriceHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPriceHistory,
                    request_deserializer=portfolio__pb2.GetPriceHistoryRequest.FromString,
                    response_serializer=portfolio__pb2.PriceHistory.SerializeToString,
            ),
            'RunBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.RunBacktest,
                    request_deserializer=portfolio__pb2.BacktestRequest.FromString,
                    response_serializer=portfolio__pb2.BacktestResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'portfolio.PortfolioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('portfolio.PortfolioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PortfolioService(object):
    """Service
    """

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portfolio.PortfolioService/Authenticate',
            portfolio__pb2.AuthRequest.SerializeToString,
            portfolio__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portfolio.PortfolioService/CreatePortfolio',
            portfolio__pb2.CreatePortfolioRequest.SerializeToString,
            portfolio__pb2.Portfolio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portfolio.PortfolioService/LoadPortfolio',
            portfolio__pb2.LoadPortfolioRequest.SerializeToString,
            portfolio__pb2.Portfolio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPortfolios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portfolio.PortfolioService/ListPortfolios',
            portfolio__pb2.ListPortfoliosRequest.SerializeToString,
            portfolio__pb2.ListPortfoliosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portfolio.PortfolioService/RunStrategy',
            portfolio__pb2.RunStrategyRequest.SerializeToString,
            portfolio__pb2.StrategyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPriceHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portfolio.PortfolioService/GetPriceHistory',
            portfolio__pb2.GetPriceHistoryRequest.SerializeToString,
            portfolio__pb2.PriceHistory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portfolio.PortfolioService/RunBacktest',
            portfolio__pb2.BacktestRequest.SerializeToString,
            portfolio__pb2.BacktestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
